#!/bin/bash
# Script to help with signed Git commits for the ChatGPT idle detection module

echo "🔐 Git Signed Commits Helper for ChatGPT Idle Detection"
echo "========================================="
echo ""
echo "To sign commits, you need to:"
echo "1. Configure GPG: git config --global user.signingkey YOUR_KEY_ID"
echo "2. Enable signing: git config --global commit.gpgsign true"
echo ""
echo "📝 Recent commits made (unsigned due to GPG passphrase requirement):"
git log --oneline -5
echo ""
echo "✅ All changes have been committed in small, atomic commits:"
echo "  - test: MutationObserver tests (TDD approach)"
echo "  - feat: ChatGPT state detector implementation"
echo "  - feat: Content script integration layer"
echo "  - chore: Jest configuration"
echo "  - docs: Solution documentation"
echo ""
echo "🚀 To push with signed commits manually:"
echo "  git commit --amend -S  # Sign the last commit"
echo "  git push origin main"
echo ""
echo "📌 Module structure preserved:"
echo "  extension.chrome/"
echo "  ├── src/"
echo "  │   ├── chatgpt-state-detector.ts"
echo "  │   ├── chatgpt-content-integration.ts"
echo "  │   └── __tests__/"
echo "  │       └── chatgpt-state-detector.test.ts"
echo "  ├── jest.config.js"
echo "  └── CHATGPT_STATE_DETECTOR_SOLUTION.md"