/**
 * Event Types for Chrome Extension Redux Store
 * All state changes are treated as events
 */

// WebSocket Connection Events
export const WEBSOCKET_CONNECTED = 'WEBSOCKET_CONNECTED';
export const WEBSOCKET_DISCONNECTED = 'WEBSOCKET_DISCONNECTED';
export const WEBSOCKET_ERROR = 'WEBSOCKET_ERROR';
export const WEBSOCKET_MESSAGE_RECEIVED = 'WEBSOCKET_MESSAGE_RECEIVED';
export const WEBSOCKET_MESSAGE_SENT = 'WEBSOCKET_MESSAGE_SENT';
export const WEBSOCKET_RECONNECTING = 'WEBSOCKET_RECONNECTING';

// ChatGPT Tab Events
export const TAB_STATE_CHANGED = 'TAB_STATE_CHANGED';
export const CHATGPT_TAB_FOUND = 'CHATGPT_TAB_FOUND';
export const CHATGPT_TAB_LOST = 'CHATGPT_TAB_LOST';
export const CHATGPT_TAB_READY = 'CHATGPT_TAB_READY';
export const CHATGPT_TAB_BUSY = 'CHATGPT_TAB_BUSY';

// Prompt Generation Events
export const PROMPT_SUBMITTED = 'PROMPT_SUBMITTED';
export const PROMPT_QUEUED = 'PROMPT_QUEUED';
export const PROMPT_PROCESSING = 'PROMPT_PROCESSING';
export const PROMPT_COMPLETED = 'PROMPT_COMPLETED';
export const PROMPT_FAILED = 'PROMPT_FAILED';
export const PROMPT_RESPONSE_RECEIVED = 'PROMPT_RESPONSE_RECEIVED';

// Image Generation Events
export const IMAGE_GENERATION_REQUESTED = 'IMAGE_GENERATION_REQUESTED';
export const IMAGE_GENERATION_STARTED = 'IMAGE_GENERATION_STARTED';
export const IMAGE_GENERATION_COMPLETED = 'IMAGE_GENERATION_COMPLETED';
export const IMAGE_GENERATION_FAILED = 'IMAGE_GENERATION_FAILED';
export const IMAGE_READY = 'IMAGE_READY';
export const IMAGE_DOWNLOAD_STARTED = 'IMAGE_DOWNLOAD_STARTED';
export const IMAGE_DOWNLOAD_COMPLETED = 'IMAGE_DOWNLOAD_COMPLETED';

// DOM Monitoring Events
export const DOM_CHANGED = 'DOM_CHANGED';
export const DOM_ELEMENT_DETECTED = 'DOM_ELEMENT_DETECTED';
export const DOM_ELEMENT_REMOVED = 'DOM_ELEMENT_REMOVED';
export const DOM_MUTATION_OBSERVED = 'DOM_MUTATION_OBSERVED';
export const TEXTAREA_DETECTED = 'TEXTAREA_DETECTED';
export const BUTTON_DETECTED = 'BUTTON_DETECTED';
export const RESPONSE_CONTAINER_DETECTED = 'RESPONSE_CONTAINER_DETECTED';

// Queue Management Events
export const QUEUE_ITEM_ADDED = 'QUEUE_ITEM_ADDED';
export const QUEUE_ITEM_REMOVED = 'QUEUE_ITEM_REMOVED';
export const QUEUE_PROCESSING_STARTED = 'QUEUE_PROCESSING_STARTED';
export const QUEUE_PROCESSING_STOPPED = 'QUEUE_PROCESSING_STOPPED';
export const QUEUE_CLEARED = 'QUEUE_CLEARED';

// Pattern Recognition Events
export const PATTERN_DETECTED = 'PATTERN_DETECTED';
export const PATTERN_LEARNED = 'PATTERN_LEARNED';
export const PATTERN_APPLIED = 'PATTERN_APPLIED';
export const PATTERN_FAILED = 'PATTERN_FAILED';

// Error Events
export const ERROR_OCCURRED = 'ERROR_OCCURRED';
export const ERROR_RECOVERED = 'ERROR_RECOVERED';
export const ERROR_RETRY_ATTEMPTED = 'ERROR_RETRY_ATTEMPTED';

// System Events
export const EXTENSION_INITIALIZED = 'EXTENSION_INITIALIZED';
export const EXTENSION_SUSPENDED = 'EXTENSION_SUSPENDED';
export const EXTENSION_RESUMED = 'EXTENSION_RESUMED';
export const CONFIG_UPDATED = 'CONFIG_UPDATED';
export const HEALTH_CHECK_PERFORMED = 'HEALTH_CHECK_PERFORMED';